import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

/** Where generated art is written. Imported by the CLI and the drift test. */
export const ART_DIR = join(REPO_ROOT, 'public', 'art');

/** Source icon for `tauri icon`. 8-bit RGBA, generated by genart. */
export const APP_ICON_PATH = join(REPO_ROOT, 'app-icon.png');

/** Desktop PNG sizes under src-tauri/icons (no iOS/Android). */
export const ICONS_DIR = join(REPO_ROOT, 'src-tauri', 'icons');
